export const DATA_DIR: any;
export const DOCUMENTS_DIR: any;
export const GDRIVE_DIR: any;
export const INVOICES_DIR: any;
export const CONTRACT_ATTACHMENTS_DIR: any;
export const CASE_ATTACHMENTS_DIR: any;
export const DB_DIR: any;
export const DB_PATH: any;
export const isRailway: any;
export function ensureDirectories(...args: any[]): any;
